#!/usr/bin/env bash
set -euo pipefail
mkdir -p downloaded_official
echo "Downloading official Rural Studio reference files..."
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2023/06/20Kv08_Dave_Floorplan_MF.pdf' -o 'downloaded_official/Dave_pdf.pdf' || echo 'FAILED: Dave_pdf.pdf'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Dave_Floorplan.png' -o 'downloaded_official/Dave_plan.png' || echo 'FAILED: Dave_plan.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Dave_Sections.png' -o 'downloaded_official/Dave_section.png' || echo 'FAILED: Dave_section.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Dave_Model-Perspective.png' -o 'downloaded_official/Dave_axon.png' || echo 'FAILED: Dave_axon.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2023/06/20Kv09_Mac_Floorplan_MF.pdf' -o 'downloaded_official/MacArthur_pdf.pdf' || echo 'FAILED: MacArthur_pdf.pdf'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Mac_Floorplan.png' -o 'downloaded_official/MacArthur_plan.png' || echo 'FAILED: MacArthur_plan.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/MacArthur_Sections.png' -o 'downloaded_official/MacArthur_section.png' || echo 'FAILED: MacArthur_section.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/MacArthur_Model-Perspective.png' -o 'downloaded_official/MacArthur_axon.png' || echo 'FAILED: MacArthur_axon.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2023/06/20Kv10_Joanne_Floorplan_MF.pdf' -o 'downloaded_official/Joanne_pdf.pdf' || echo 'FAILED: Joanne_pdf.pdf'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Joanne_Floorplan.png' -o 'downloaded_official/Joanne_plan.png' || echo 'FAILED: Joanne_plan.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Joanne_Sections.png' -o 'downloaded_official/Joanne_section.png' || echo 'FAILED: Joanne_section.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Joanne_Model-Perspective.png' -o 'downloaded_official/Joanne_axon.png' || echo 'FAILED: Joanne_axon.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2023/06/Sylvia-2-1_Floorplan.pdf' -o 'downloaded_official/Sylvia_2-1_pdf.pdf' || echo 'FAILED: Sylvia_2-1_pdf.pdf'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Sylvia-2-1_Floorplan-Final.png' -o 'downloaded_official/Sylvia_2-1_plan.png' || echo 'FAILED: Sylvia_2-1_plan.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2022/08/Sylvia-2-1_Section.png' -o 'downloaded_official/Sylvia_2-1_section.png' || echo 'FAILED: Sylvia_2-1_section.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2024/03/Sylvia-2-2_Floorplan.pdf' -o 'downloaded_official/Sylvia_2-2_pdf.pdf' || echo 'FAILED: Sylvia_2-2_pdf.pdf'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2024/02/Sylvia-2-2_Floorplan-1.png' -o 'downloaded_official/Sylvia_2-2_plan.png' || echo 'FAILED: Sylvia_2-2_plan.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2024/02/Sylvia2-2_Sections.png' -o 'downloaded_official/Sylvia_2-2_section.png' || echo 'FAILED: Sylvia_2-2_section.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2024/03/Sylvia-3-2_Floorplan.pdf' -o 'downloaded_official/Sylvia_3-2_pdf.pdf' || echo 'FAILED: Sylvia_3-2_pdf.pdf'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2024/02/Sylvia-3-2_Floorplan-slider.png' -o 'downloaded_official/Sylvia_3-2_plan.png' || echo 'FAILED: Sylvia_3-2_plan.png'
curl -L --fail --retry 2 'https://frontporch.ruralstudio.org/wp-content/uploads/2024/02/Sylvia3bd_Sections.png' -o 'downloaded_official/Sylvia_3-2_section.png' || echo 'FAILED: Sylvia_3-2_section.png'
curl -L --fail --retry 2 'https://ruralstudio.org/wp-content/uploads/2019/06/REV-WALKER-HURSLEY-HEADER-scaled.jpg' -o 'downloaded_official/Rev_Walker_official.jpg' || echo 'FAILED: Rev_Walker'
curl -L --fail --retry 2 'https://ruralstudio.org/wp-content/uploads/2021/07/Walker_AdditionDiagram_Edited.jpg' -o 'downloaded_official/Rev_Walker_Addition_official.jpg' || echo 'FAILED: Rev_Walker_Addition'
curl -L --fail --retry 2 'https://ruralstudio.org/wp-content/uploads/2019/06/HURSLEY-HEADER-REDUCED.jpg' -o 'downloaded_official/Myers_official.jpg' || echo 'FAILED: Myers'
curl -L --fail --retry 2 'https://ruralstudio.org/wp-content/uploads/2019/06/bridgehouse-featured.jpg' -o 'downloaded_official/Bridge_official.jpg' || echo 'FAILED: Bridge'
curl -L --fail --retry 2 'https://ruralstudio.org/wp-content/uploads/2019/06/Harris-Butterfly-header-image.jpg' -o 'downloaded_official/Butterfly_official.jpg' || echo 'FAILED: Butterfly'
curl -L --fail --retry 2 'https://ruralstudio.org/wp-content/uploads/2019/06/lucy-featured.jpg' -o 'downloaded_official/Lucy_official.jpg' || echo 'FAILED: Lucy'
