// EVERY LINK IN THE TWO PAGES WE ASK PEOPLE TO OPEN.
//
// index.html and issue-for-review.html are both GENERATED by walking the
// repository, which makes a dead link unlikely and not impossible: a generator
// can name a file it expects rather than one it found, and nothing has ever
// checked. These are the two documents a surveyor, an engineer or a builder is
// asked to open, and a 404 in one of them costs their goodwill before they
// have read a word.
//
// So: resolve every local href and src in both, against the working tree.
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const PAGES = ['index.html', 'issue-for-review.html', 'site.html', 'trace.html'];

console.log('HENRY HOUSE — DO THE LINKS RESOLVE');
console.log('='.repeat(72));

let broken = 0, checked = 0, pages = 0;
for (const page of PAGES) {
  const path = resolve(ROOT, page);
  if (!existsSync(path)) { console.log(`  ✗ ${page.padEnd(24)} the page itself is missing`); broken++; continue; }
  const html = readFileSync(path, 'utf8');
  const refs = new Set();
  for (const m of html.matchAll(/(?:href|src)\s*=\s*"([^"]+)"/g)) {
    const u = m[1];
    if (/^(https?:|mailto:|data:|#|\/\/)/.test(u)) continue;   // external or in-page
    // A URL built at runtime inside a template literal is not a static link and
    // cannot be resolved against the tree. Flagging it was a false positive of
    // this checker, not a broken link in the page.
    if (u.includes('${')) continue;
    refs.add(u.split('#')[0].split('?')[0]);
  }
  const bad = [];
  for (const r of refs) {
    if (!r) continue;
    checked++;
    if (!existsSync(resolve(dirname(path), r))) bad.push(r);
  }
  pages++;
  if (bad.length) {
    broken += bad.length;
    console.log(`  ✗ ${page.padEnd(24)} ${bad.length} of ${refs.size} local links do not resolve`);
    for (const b of bad.slice(0, 8)) console.log(`        · ${b}`);
    if (bad.length > 8) console.log(`        · + ${bad.length - 8} more`);
  } else {
    console.log(`  ✓ ${page.padEnd(24)} all ${refs.size} local links resolve`);
  }
}

console.log('='.repeat(72));
console.log(`RESULT         ${broken} broken, ${checked} checked across ${pages} page${pages === 1 ? '' : 's'}`);
process.exit(broken ? 1 : 0);
