// PULL THE REAL GROUND OUT OF CREO AND INTO THIS MODEL.
//
// Every render in this project so far stands on a synthetic plane: 30% one way,
// 8% the other, perfectly smooth, at no particular place on earth. That plane
// turned out to have the slope right and the direction wrong (docs/09).
//
// CREO holds a measured heightfield for the parcel the client named. This
// writes the part of it that surrounds the house into model/site-terrain.mjs,
// so the schemes can be rendered standing on the actual hill.
//
//   node tools/extract-terrain.mjs <place.json> [--half=500]
//
// The DEM is 31 m per sample. That is coarse — it renders the shape of the
// hillside honestly and cannot show the bench a house would really sit on.
import { readFileSync, writeFileSync } from 'node:fs';
import { SITE } from '../model/geometry.mjs';

const args = process.argv.slice(2);
const file = args.find((a) => !a.startsWith('--'));
const halfM = Number((args.find((a) => a.startsWith('--half=')) || '--half=520').split('=')[1]);
if (!file) { console.error('usage: node tools/extract-terrain.mjs <place.json> [--half=520]'); process.exit(2); }

const doc = JSON.parse(readFileSync(file, 'utf8'));
const P = doc.place, T = P.terrain;
const heights = T.f32
  ? new Float32Array(Uint8Array.from(Buffer.from(T.f32, 'base64')).buffer)
  : Float32Array.from(T.data);
const cell = T.cell;
const nx = Math.round((T.bounds[2] - T.bounds[0]) / cell) + 1;
const ny = Math.round((T.bounds[3] - T.bounds[1]) / cell) + 1;
const at = (i, j) => heights[Math.max(0, Math.min(ny - 1, j)) * nx + Math.max(0, Math.min(nx - 1, i))];
const groundAt = (e, n) => {                     // bilinear, metres above meta.datum
  const fx = (e - T.bounds[0]) / cell, fy = (n - T.bounds[1]) / cell;
  const i = Math.floor(fx), j = Math.floor(fy), u = fx - i, v = fy - j;
  return (at(i, j) * (1 - u) + at(i + 1, j) * u) * (1 - v) +
         (at(i, j + 1) * (1 - u) + at(i + 1, j + 1) * u) * v;
};

// Sample on the HOUSE's axes, not the compass, so the stored grid needs no
// rotation at render time: +u runs along the contour, +v runs uphill.
const UP = (SITE.fallsToAzimuth + 180) % 360, rad = Math.PI / 180;
const uy = [Math.sin(UP * rad), Math.cos(UP * rad)];
const ux = [Math.sin((UP + 90) * rad), Math.cos((UP + 90) * rad)];
const toEN = (u, v) => [u * ux[0] + v * uy[0], u * ux[1] + v * uy[1]];

const step = cell;                                // keep the DEM's own resolution
const n = Math.round((halfM * 2) / step) + 1;
const z0 = groundAt(...toEN(0, 0));               // the anchor's own ground
const grid = [];
for (let j = 0; j < n; j++) {
  for (let i = 0; i < n; i++) {
    const u = -halfM + i * step, v = -halfM + j * step;
    // metres relative to the anchor's ground — the model's own datum is set
    // from this, so the origin keeps sitting where the synthetic plane put it
    grid.push(+(groundAt(...toEN(u, v)) - z0).toFixed(2));
  }
}

const lo = Math.min(...grid), hi = Math.max(...grid);
const body = `// HENRY HOUSE — THE ACTUAL GROUND AT THE PARCEL.
//
// GENERATED by tools/extract-terrain.mjs from CREO's measured heightfield for
// ${P.name}. DO NOT HAND-EDIT.
//
// Heights are METRES relative to the ground at the anchor, sampled on the
// HOUSE's axes: +u along the contour, +v uphill. Uphill is azimuth ${UP}°,
// because the land falls to ${SITE.fallsToAzimuth}° — see docs/09.
//
// Source:  ${P.meta.elevation}
//          ${P.meta.licence}
// Anchor:  ${P.anchor[0].toFixed(6)}, ${P.anchor[1].toFixed(6)}  (${SITE.elevationFtAmsl} ft AMSL)
// Extent:  ±${halfM} m at ${step.toFixed(1)} m — ${n}×${n} samples
// Relief:  ${lo.toFixed(1)} to ${hi.toFixed(1)} m about the anchor
//
// 31 m is a hillside, not a building site. It renders the shape of this ground
// honestly. It cannot show the bench a house would really stand on.
export const SITE_TERRAIN = {
  n: ${n},
  step: ${step},
  half: ${halfM},
  anchorFtAmsl: ${SITE.elevationFtAmsl},
  uphillAzimuth: ${UP},
  source: ${JSON.stringify(P.meta.elevation)},
  licence: ${JSON.stringify(P.meta.licence)},
  h: ${JSON.stringify(grid)},
};

const M_PER_IN = 0.0254;

/**
 * Ground height in model INCHES at model (x, y) inches — x along the contour,
 * y uphill, exactly the convention every scheme is drawn in. Bilinear, and
 * clamped at the edge so a wide camera does not fall off the data.
 */
export function siteGrade(xIn, yIn) {
  const S = SITE_TERRAIN;
  const fx = (xIn * M_PER_IN + S.half) / S.step;
  const fy = (yIn * M_PER_IN + S.half) / S.step;
  const i = Math.max(0, Math.min(S.n - 2, Math.floor(fx)));
  const j = Math.max(0, Math.min(S.n - 2, Math.floor(fy)));
  const u = Math.max(0, Math.min(1, fx - i)), v = Math.max(0, Math.min(1, fy - j));
  const H = (a, b) => S.h[b * S.n + a];
  const m = (H(i, j) * (1 - u) + H(i + 1, j) * u) * (1 - v) +
            (H(i, j + 1) * (1 - u) + H(i + 1, j + 1) * u) * v;
  // −6 in keeps the origin's ground exactly where the synthetic plane put it,
  // so a scheme's floor levels mean the same thing on either ground.
  return -6 + m / M_PER_IN;
}

export default { SITE_TERRAIN, siteGrade };
`;

writeFileSync(new URL('../model/site-terrain.mjs', import.meta.url), body);
console.log('HENRY HOUSE — REAL GROUND');
console.log('='.repeat(66));
console.log(`  place    ${P.name}`);
console.log(`  extent   ±${halfM} m at ${step.toFixed(1)} m  →  ${n}×${n} = ${grid.length} samples`);
console.log(`  relief   ${lo.toFixed(1)} to ${hi.toFixed(1)} m about the anchor` +
            `  (${((hi - lo) * 3.28084).toFixed(0)} ft across the window)`);
console.log(`  uphill   azimuth ${UP}°`);
console.log('  → model/site-terrain.mjs');
