import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { buildScene } from '../tools/render/lib/scene.mjs';
import { sunDirection } from '../tools/render/lib/render.mjs';
import { SITE_SLOPE } from '../model/geometry.mjs';
import { SITE_CONTEXT, PARCEL_LONLAT, ROAD_LOCAL_FT, HIGHWAY_LOCAL_FT, PARCEL_LOCAL_FT, lonLatToLocalFt, localFtToLonLat } from '../model/site-context.mjs';
import { similarityRegistration, boundsOf, findHouseCandidates, localToWorld, worldToLocal, routeDrive, profileDrive } from './site-fit.mjs';

const DEFAULT_AZ = 252;
const byId=id=>document.getElementById(id);
const el={};['load','loadText','menu','panel','site','drive','house','aerial','terrainMetric','imageryMetric','driveMetric','fitMetric','cutFillMetric','az','azv','off','reset','parcel','roads','satellite','proposal','fast','detail','prov','status','statusTitle','statusText','candidateButtons'].forEach(id=>el[id]=byId(id));
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<760;
const renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});renderer.setPixelRatio(mobile?1:Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=!mobile;document.body.prepend(renderer.domElement);
const built=buildScene(renderer,{sun:sunDirection({dayOfYear:288,hour:14}),realtime:true});const scene=built.scene,rig=built.rig;scene.fog=new THREE.FogExp2(0xb8c5c8,.00015);
const groups=scene.children.filter(x=>x.type==='Group'&&x.name!=='SYSTEMS');const [shell,interior,frames,oldDrive,veg,ridges]=groups;for(const g of[oldDrive,veg,ridges])if(g)scene.remove(g);const oldTerrain=scene.children.find(x=>x.isMesh&&x.geometry?.type==='PlaneGeometry'&&Math.abs((x.geometry.parameters?.width||0)-900)<2);if(oldTerrain)scene.remove(oldTerrain);if(built.systems?.group)built.systems.group.visible=false;if(interior)interior.visible=!mobile;
const placementRoot=new THREE.Group(),architecture=new THREE.Group();scene.add(placementRoot);placementRoot.add(architecture);for(const x of[shell,interior,frames])if(x)architecture.attach(x);
const P=SITE_CONTEXT.placement;architecture.position.set(-P.modelPivotXFt,0,P.modelPivotYFt);const modelGround=SITE_SLOPE.grade(P.modelPivotXFt*12,P.modelPivotYFt*12)/12;
const camera=new THREE.PerspectiveCamera(mobile?58:52,innerWidth/innerHeight,.5,12000),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=false;orbit.maxPolarAngle=Math.PI*.495;orbit.maxDistance=7000;let rq=false;function draw(){if(rq)return;rq=true;requestAnimationFrame(()=>{rq=false;renderer.render(scene,camera)})}orbit.addEventListener('change',draw);
function status(title,text,warn=false){el.statusTitle.textContent=title;el.statusText.textContent=text;el.status.classList.toggle('warn',warn)}

let parcelPts=PARCEL_LOCAL_FT.map(p=>({...p})),parcelLL=PARCEL_LONLAT.slice(),roadPts=ROAD_LOCAL_FT.map(p=>({...p})),highwayPts=HIGHWAY_LOCAL_FT.map(p=>({...p}));let H=(e,n)=>0,anchorM=0,aerialTexture=null,terrainBounds=null,terrainRange={min:0,max:0},terrainMesh=null,parcelMesh=null,roadMesh=null,highwayMesh=null,proposalMesh=null,padMesh=null,candidateMeshes=[],drivePath=[];let candidates=[],choice=0,east=0,north=0,az=DEFAULT_AZ,houseBase=0,houseFit=null;
const DEM_Z=15,cache=new Map(),tileX=(lon,z)=>(lon+180)/360*2**z,tileY=(lat,z)=>(1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*2**z,lonAt=(x,z)=>x/2**z*360-180,latAt=(y,z)=>Math.atan(Math.sinh(Math.PI*(1-2*y/2**z)))*180/Math.PI,key=(x,y)=>`${DEM_Z}/${x}/${y}`;
function image(url){return new Promise((ok,no)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>ok(i);i.onerror=()=>no(Error(url));i.src=url})}async function demTile(x,y){if(cache.has(key(x,y)))return;const im=await image(`https://s3.amazonaws.com/elevation-tiles-prod/terrarium/${DEM_Z}/${x}/${y}.png`),c=document.createElement('canvas');c.width=c.height=256;const q=c.getContext('2d',{willReadFrequently:true});q.drawImage(im,0,0);cache.set(key(x,y),q.getImageData(0,0,256,256).data)}function em(lon,lat){const X=tileX(lon,DEM_Z),Y=tileY(lat,DEM_Z),a=Math.floor(X),b=Math.floor(Y),d=cache.get(key(a,b));if(!d)return null;const px=Math.max(0,Math.min(255,Math.floor((X-a)*256))),py=Math.max(0,Math.min(255,Math.floor((Y-b)*256))),i=(py*256+px)*4;return d[i]*256+d[i+1]+d[i+2]/256-32768}
async function officialParcel(){const base='https://maps.cot.tn.gov/server3/rest/services/IMPACT/Parcels/FeatureServer/0/query',q=new URLSearchParams({where:'1=1',geometry:`${SITE_CONTEXT.anchor.lon},${SITE_CONTEXT.anchor.lat}`,geometryType:'esriGeometryPoint',inSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'GISLINK,GISLINK2,CALC_ACRE,PARCELWP,COUNTY_ID',returnGeometry:'true',outSR:'4326',f:'geojson'});const r=await fetch(`${base}?${q}`);if(!r.ok)throw Error(r.status);const d=await r.json(),f=(d.features||[]).filter(x=>x.geometry).sort((a,b)=>Math.abs((a.properties?.CALC_ACRE??999)-29.34)-Math.abs((b.properties?.CALC_ACRE??999)-29.34))[0];if(!f)throw Error('no parcel');const rings=f.geometry.type==='Polygon'?f.geometry.coordinates:f.geometry.coordinates.flat(),ring=rings.slice().sort((a,b)=>b.length-a.length)[0],dst=ring.map(([lon,lat])=>lonLatToLocalFt(lon,lat)),reg=similarityRegistration(parcelPts,dst);roadPts=roadPts.map(reg.transform);highwayPts=highwayPts.map(reg.transform);parcelPts=dst;parcelLL=ring;el.prov.textContent=`Tennessee Comptroller parcel loaded. Screenshot roads registered by rotation + scale; fit RMS ${reg.rmsFt.toFixed(0)} ft.`}
async function terrain(){const b=boundsOf([...parcelPts,...roadPts,...highwayPts],260),sw=localFtToLonLat(b.minE,b.minN),ne=localFtToLonLat(b.maxE,b.maxN),x0=Math.floor(tileX(sw.lon,DEM_Z)),x1=Math.floor(tileX(ne.lon,DEM_Z)),y0=Math.floor(tileY(ne.lat,DEM_Z)),y1=Math.floor(tileY(sw.lat,DEM_Z)),jobs=[];for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)jobs.push(demTile(x,y));await Promise.all(jobs);anchorM=em(SITE_CONTEXT.anchor.lon,SITE_CONTEXT.anchor.lat);H=(e,n)=>{const ll=localFtToLonLat(e,n),m=em(ll.lon,ll.lat);return Number.isFinite(m)?(m-anchorM)*3.280839895:0};el.terrainMetric.textContent=`DEM · anchor ${Math.round(anchorM*3.28084)} ft`}
async function aerial(){const Z=mobile?16:17,b=boundsOf([...parcelPts,...roadPts,...highwayPts],300),sw=localFtToLonLat(b.minE,b.minN),ne=localFtToLonLat(b.maxE,b.maxN),x0=Math.floor(tileX(sw.lon,Z)),x1=Math.floor(tileX(ne.lon,Z)),y0=Math.floor(tileY(ne.lat,Z)),y1=Math.floor(tileY(sw.lat,Z));const nx=x1-x0+1,ny=y1-y0+1;if(nx*ny>24)throw Error('imagery window');const c=document.createElement('canvas');c.width=nx*256;c.height=ny*256;const q=c.getContext('2d'),jobs=[];for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)jobs.push(image(`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${Z}/${y}/${x}`).then(im=>q.drawImage(im,(x-x0)*256,(y-y0)*256)));await Promise.all(jobs);aerialTexture=new THREE.CanvasTexture(c);aerialTexture.colorSpace=THREE.SRGBColorSpace;const p0=lonLatToLocalFt(lonAt(x0,Z),latAt(y1+1,Z)),p1=lonLatToLocalFt(lonAt(x1+1,Z),latAt(y0,Z));terrainBounds={minE:p0.east,maxE:p1.east,minN:p0.north,maxN:p1.north};el.imageryMetric.textContent=`World Imagery · z${Z}`}
function ribbon(points,width,color,lift=2,opacity=1,zOverride=false){const pos=[],idx=[],half=width/2;for(let i=0;i<points.length;i++){const a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],dx=b.east-a.east,dz=-(b.north-a.north),L=Math.hypot(dx,dz)||1,nx=dz/L,nz=dx/L;for(const s of[-1,1]){const x=points[i].east+nx*half*s,Z=-points[i].north+nz*half*s;pos.push(x,(zOverride&&Number.isFinite(points[i].z)?points[i].z:H(x,-Z))+lift,Z)}if(i<points.length-1){const j=i*2;idx.push(j,j+2,j+1,j+1,j+2,j+3)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);return new THREE.Mesh(g,new THREE.MeshBasicMaterial({color,transparent:opacity<1,opacity,side:THREE.DoubleSide,depthWrite:opacity>=1}))}
function buildTerrain(){const b=terrainBounds||boundsOf([...parcelPts,...roadPts,...highwayPts],300),g=new THREE.PlaneGeometry(b.maxE-b.minE,b.maxN-b.minN,mobile?72:120,mobile?72:120);g.rotateX(-Math.PI/2);const p=g.attributes.position,cE=(b.minE+b.maxE)/2,cN=(b.minN+b.maxN)/2;let lo=Infinity,hi=-Infinity;for(let i=0;i<p.count;i++){const e=p.getX(i)+cE,n=-p.getZ(i)+cN,h=H(e,n);p.setX(i,e);p.setZ(i,-n);p.setY(i,h);lo=Math.min(lo,h);hi=Math.max(hi,h)}g.computeVertexNormals();terrainRange={min:lo,max:hi};terrainMesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({map:aerialTexture,color:aerialTexture?0xffffff:0x5d6655,roughness:1}));scene.add(terrainMesh);parcelMesh=ribbon(parcelPts,6,0xffcf55,3);roadMesh=ribbon(roadPts,11,0xf3eee1,3,.95);highwayMesh=ribbon(highwayPts,6,0xf3eee1,3,.72);scene.add(parcelMesh,roadMesh,highwayMesh)}
const fit={x0:-60,x1:60,y0:-42,y1:42};const modelRelativeGrade=(x,y)=>.08*x+.30*y;
function chooseCandidates(){candidates=findHouseCandidates({H,parcelPts,roadPts,terrainMin:terrainRange.min,terrainMax:terrainRange.max,fit,modelRelativeGrade,step:mobile?70:52,count:3});if(!candidates.length)candidates=[{east:0,north:0,az:DEFAULT_AZ,fit:{base:H(0,0),rms:999,max:999},roadDistance:999}];el.candidateButtons.innerHTML='';candidates.forEach((c,i)=>{const b=document.createElement('button');b.textContent=String.fromCharCode(65+i);b.onclick=()=>selectCandidate(i);el.candidateButtons.appendChild(b);const m=new THREE.Mesh(new THREE.CylinderGeometry(7,7,2,18),new THREE.MeshBasicMaterial({color:i?0xffffff:0xe6784e,transparent:true,opacity:.75}));m.position.set(c.east,H(c.east,c.north)+3,-c.north);scene.add(m);candidateMeshes.push(m)});selectCandidate(0)}
function smooth01(t){t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)}
function finishedHeight(e,n){if(!terrainMesh)return H(e,n);const q=worldToLocal(e,n,east,north,az),coreX=88,coreY=62,blend=52,dx=Math.max(0,Math.abs(q.x)-coreX),dy=Math.max(0,Math.abs(q.y)-coreY),d=Math.hypot(dx,dy);if(d<=0)return houseBase;if(d>=blend)return H(e,n);const t=smooth01(d/blend);return houseBase*(1-t)+H(e,n)*t}
function reshapeTerrain(){if(!terrainMesh)return;const p=terrainMesh.geometry.attributes.position;let cut=0,fill=0,count=0;for(let i=0;i<p.count;i++){const e=p.getX(i),n=-p.getZ(i),natural=H(e,n),finished=finishedHeight(e,n),delta=finished-natural;p.setY(i,finished);if(Math.abs(delta)>.05){count++;if(delta>0)fill+=delta;else cut-=delta}}p.needsUpdate=true;terrainMesh.geometry.computeVertexNormals();el.cutFillMetric.textContent=`flat bench · ${count} terrain samples reshaped · cut ${cut.toFixed(0)} / fill ${fill.toFixed(0)} ft-sample`}
function housePad(){if(padMesh){scene.remove(padMesh);padMesh.geometry.dispose()}const pts=[];for(let i=0;i<24;i++){const a=i/24*Math.PI*2,x=Math.cos(a)*88,y=Math.sin(a)*62,p=localToWorld(x,y,east,north,az);pts.push(new THREE.Vector3(p.east,houseBase+1.5,-p.north))}const sh=new THREE.Shape();pts.forEach((p,i)=>i?sh.lineTo(p.x,p.z):sh.moveTo(p.x,p.z));sh.closePath();const g=new THREE.ShapeGeometry(sh);g.rotateX(-Math.PI/2);padMesh=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0xc8b88f,transparent:true,opacity:.72,side:THREE.DoubleSide}));padMesh.position.y=houseBase+1.5;scene.add(padMesh)}
function buildDrive(){if(proposalMesh){scene.remove(proposalMesh);proposalMesh.geometry.dispose();proposalMesh=null}const garage=localToWorld(65,28,east,north,az),start=roadPts[0],path=routeDrive({H,parcelPts,start,goal:garage,maxGrade:.15,step:mobile?30:24});if(!path){el.driveMetric.textContent='no route ≤ ~17.5% found';return}const prof=profileDrive(H,path,houseBase+8,.12);drivePath=prof;proposalMesh=ribbon(prof,12,0xe6784e,3,1,true);scene.add(proposalMesh);let len=0,maxG=0;for(let i=1;i<prof.length;i++){const a=prof[i-1],b=prof[i],run=Math.hypot(b.east-a.east,b.north-a.north);len+=run;maxG=Math.max(maxG,Math.abs(b.z-a.z)/(run||1))}el.driveMetric.textContent=`${Math.round(len)} ft · max ${Math.round(maxG*100)}%`}
function place(){placementRoot.rotation.y=THREE.MathUtils.degToRad(90-az);placementRoot.position.set(east,houseBase-modelGround,-north);el.az.value=String(Math.round(az));el.azv.textContent=`${Math.round(az)}°`;el.off.textContent=`E ${Math.round(east)} ft · N ${Math.round(north)} ft`;reshapeTerrain();housePad();buildDrive();draw()}
function selectCandidate(i){choice=i;const c=candidates[i];east=c.east;north=c.north;az=DEFAULT_AZ;houseBase=H(east,north);houseFit=c.fit;[...el.candidateButtons.children].forEach((b,j)=>b.classList.toggle('on',i===j));el.fitMetric.textContent=`candidate ${String.fromCharCode(65+i)} · fixed bearing 252° · flat finished bench`;place();viewHouse()}
function siteMetrics(){const b=boundsOf([...parcelPts,...roadPts,...highwayPts],0),span=Math.max(b.maxE-b.minE,b.maxN-b.minN);return{center:new THREE.Vector3((b.minE+b.maxE)/2,(terrainRange.min+terrainRange.max)/2,-(b.minN+b.maxN)/2),span}}
function activate(k){for(const id of['site','drive','house','aerial'])el[id].classList.toggle('on',id===k)}function viewSite(){const m=siteMetrics();camera.position.set(m.center.x-m.span*.28,terrainRange.max+m.span*.36,m.center.z+m.span*.62);orbit.target.copy(m.center);orbit.update();activate('site')}function viewAerial(){const m=siteMetrics();camera.position.set(m.center.x,terrainRange.max+m.span*.92,m.center.z+m.span*.06);orbit.target.copy(m.center);orbit.update();activate('aerial')}function viewHouse(){camera.position.set(east-125,houseBase+82,-north+150);orbit.target.set(east,houseBase+16,-north);orbit.update();activate('house')}function viewDrive(){const p=drivePath.length?drivePath:roadPts,a=p[0],b=p[Math.min(p.length-1,Math.max(1,Math.floor(p.length*.35)))];camera.position.set(a.east-55,H(a.east,a.north)+45,-a.north+55);orbit.target.set(b.east,H(b.east,b.north)+10,-b.north);orbit.update();activate('drive')}
function quality(detail){renderer.setPixelRatio(detail?Math.min(devicePixelRatio,mobile?1.25:1.7):1);renderer.shadowMap.enabled=detail&&!mobile;rig.sun.castShadow=detail&&!mobile;rig.skyLight.visible=detail&&!mobile;if(interior)interior.visible=detail||!mobile;el.fast.classList.toggle('on',!detail);el.detail.classList.toggle('on',detail);renderer.setSize(innerWidth,innerHeight);draw()}
el.menu.onclick=()=>{const on=el.panel.classList.toggle('on');el.menu.textContent=on?'×':'≡'};el.site.onclick=viewSite;el.drive.onclick=viewDrive;el.house.onclick=viewHouse;el.aerial.onclick=viewAerial;el.az.oninput=e=>{az=+e.target.value;houseBase=H(east,north);place()};document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const d=b.dataset.d;if(d==='n')north+=10;if(d==='s')north-=10;if(d==='e')east+=10;if(d==='w')east-=10;houseBase=H(east,north);place()});el.reset.onclick=()=>selectCandidate(choice);el.parcel.onclick=()=>{parcelMesh.visible=!parcelMesh.visible;el.parcel.classList.toggle('on',parcelMesh.visible);draw()};el.roads.onclick=()=>{const on=!roadMesh.visible;roadMesh.visible=highwayMesh.visible=on;el.roads.classList.toggle('on',on);draw()};el.satellite.onclick=()=>{const on=!terrainMesh.material.map;terrainMesh.material.map=on?aerialTexture:null;terrainMesh.material.color.set(on&&aerialTexture?0xffffff:0x5d6655);terrainMesh.material.needsUpdate=true;el.satellite.classList.toggle('on',on);draw()};el.proposal.onclick=()=>{if(!proposalMesh)return;proposalMesh.visible=!proposalMesh.visible;el.proposal.classList.toggle('on',proposalMesh.visible);draw()};el.fast.onclick=()=>quality(false);el.detail.onclick=()=>quality(true);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);draw()});
try{el.loadText.textContent='Locating cadastral parcel…';await officialParcel()}catch(e){el.prov.textContent='Official parcel unavailable; screenshot boundary retained.'}try{el.loadText.textContent='Loading terrain…';await terrain()}catch(e){status('TERRAIN ERROR','DEM failed; site fit cannot be trusted',true);throw e}try{el.loadText.textContent='Loading aerial imagery…';await aerial()}catch(e){el.imageryMetric.textContent='unavailable';aerialTexture=null}buildTerrain();chooseCandidates();quality(!mobile);viewSite();status('SITE FIT','default bearing 252° · flat finished bench · existing road + generated driveway');el.load.remove();draw();
